line-length = 80
indent-width = 2

# Assume Python 3.11
target-version = "py311"


# Ignore some import violations when not needed
[lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]
